import Head from "next/head";
import { ApiHandler } from "~/service/UtilService";
import { useEffect, useMemo, useState } from "react";
import React from "react";
import { decryptResponse } from "~/helpers/helper";

export default function Home() {
  const [tabName, setTabName] = useState<string>(
    "Exchange your crypto currencies",
  );

  useEffect(() => {
    void fetchAdmin();
  }, []);

  async function fetchAdmin() {
    try {
      const adminTab = await fetch(
        `${process.env.NEXT_PUBLIC_API_BASE_URL}/admin/admin-profile`,
      );
      const res = await adminTab.json();
      const result = decryptResponse(res);
      setTabName(result?.body[0]?.tabName);
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <Head>
      <title>{tabName}</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
